[package]
name = "hybrid-example"
version = "1.0.0"
authors = []

[addresses]
hybrid_example_addr = "_"
hybrid_address = "0xbbe8a08f3b9774fccb31e02def5a79f1b7270b2a1cb9ffdc05b2622813298f2a"
deployer = "0xaddedfb9bd74560e1c2cd00137e8db9a9b28bbcea3361f2e48ca52331c850c95"

[dev-addresses]
hybrid_example_addr = "0xCAFE"

[dependencies.hybrid]
local = "../hybrid-base"

[dev-dependencies]
